### ISSUE TITLE
JS || Funtion that adds UserDetails in students profile Code Improvements

### ISSUE THREAD

**Issue by DarioDeLaFuente** [NoroffFEU/agency.noroff.dev#246]
The following needs to be updated:

- [x] POST Key/values matching that of the ``profile/users`` ``API`` response object.
- [x] POST/ GET Key/values matching that of the ``profile/users/{id}`` ``API`` response object.
- [x] PUT Key/values matching that of the ``profile/users/{id}`` ``API`` response object.

### **Api DOC** 
* https://agency-api.noroff.dev/api-docs/#/

- [x] Updated logic to handle views:
- [x]  Profile user(own)Details.
- [ ] Profile user (other)Details.

### **Task** 
- [x] Improvement cod that gets id/user details from local storage or api
- [x] And add the out to the predefined profile template.

**Comment by DarioDeLaFuente** [comment]
Working branch: git:(modern-forge-Profile-login-UserDetails)

Updated logic to handle views:Profile user(own)
Logic flow api endpoit weiw:https://www.figma.com/file/i0RCnWcTigbKr9JKrRuUVe/Site-Map-%2F-User-Flow---Responsive-Component-(Community)?type=design&node-id=2-48&mode=design&t=45oW5WOUDux9PiWg-0


figma wiewus:
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/16e71dc8-b5fa-44fd-9354-eb4e9688cb73)


 Local wiewus:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/a1b488b3-18c5-41fa-b462-965e4c423bde)

**Comment by DarioDeLaFuente** [comment]
Hi @Fermain 

If I think correctly, the bag I made is a continuation of this one:
https://github.com/NoroffFEU/agency.noroff.dev/pull/204

Isn't it REF:
![](file:///var/folders/mn/gb60rh5s4h1886dmpflvx1g00000gn/T/TemporaryItems/NSIRD_screencaptureui_LRXz4g/Screenshot%202023-09-29%20at%2019.48.13.png)

**Comment by DarioDeLaFuente** [comment]
The endpoint is Wonki :) skills doc sess that I take a string example: List [ "HTML", "CSS", "JavaScript", "Git", "GitHub" ]skills this user has.

but it has to be a string: "skills":"HTML,CSS,JavaScript,Git,GitHub,JavaScript,Git,GitHub"
--


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/bc2b325c-c310-4914-8e1f-a79624cb7a36)



![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/fd17bf7a-a691-472b-841c-58918832b3ee)

**Comment by Fermain** [comment]
Hey @DarioDeLaFuente can you raise a new issue for this as a bug?

**Comment by DarioDeLaFuente** [comment]
This is solved in another task: Ref:Jøran Engelund - Frontend-Legacy — Yesterday at 16:28
But isn’t the issue that the skills property from the user endpoint a string for skills value. While it should be a array containing string items? 
Alexander, Backend-Legacy — Yesterday at 16:30
I thought we fixed that, but that fix might be in the dev branch, when I have the time to commit to it I will double check.
Ref:https://discord.com/channels/1089795633910657026/1089798372141047868/1158772607789842564


But I can't find that bag/task. @Fermain
