### ISSUE TITLE
JS || Funtion that adds listings in students profile Code Improvements

### ISSUE THREAD

**Issue by DarioDeLaFuente** [NoroffFEU/agency.noroff.dev#247]
The following needs to be updated:

- [x] POST Key/values matching that of the ``profile/listings`` ``API`` response object.
- [x] GET Key/values matching that of the ``profile/listings`` ``API`` response object.
- [x] GET Key/values matching that of the ``profile/listings/{id}`` ``API`` response object.

###Task
- [ ] Updated logic to handle listings views:
- Profile user(own) /listings
- Profile user (other)/listings/{id}

**Comment by DarioDeLaFuente** [comment]
Working branch: git:(modern-forge-Profile-login-UserDetails)

Updated logic to handle views:Profile user listing (own)
Logic flow api endpoit weiw:https://www.figma.com/file/i0RCnWcTigbKr9JKrRuUVe/Site-Map-%2F-User-Flow---Responsive-Component-(Community)?type=design&node-id=2-48&mode=design&t=45oW5WOUDux9PiWg-0


figma wiewus:
![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/bf247446-52d0-46df-83c3-9254fcd6a7dd)



 Local wiewus:


![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/33604162/a1b488b3-18c5-41fa-b462-965e4c423bde)

**Comment by DarioDeLaFuente** [comment]
@Fermain is my branch a duplicate ofthis https://github.com/NoroffFEU/agency.noroff.dev/issues/51 or should I create this function?

**Comment by runeunhjem** [comment]
Closing this as there is no history the last 3 months
